openapi: 3.0.3
info:
    title: rosenzu Example
    description: 路線図を書くためのデータ
    version: v1
servers:
    - url: http://localhost:8000/api/v1
paths:
    /line/{name}:
        get:
            tags:
                - rosenzu
            summary: find rosenzu
            operationId: rosenzu#find
            parameters:
                - name: name
                  in: path
                  description: 路線名
                  required: true
                  schema:
                    type: string
                    description: 路線名
                    example: Excepturi ipsum eum fugit.
                  example: Corrupti alias.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Line'
                            example:
                                elements:
                                    - coordinates:
                                        - latitude: 138.854723
                                          longitude: 37.446707
                                        - latitude: 138.854723
                                          longitude: 37.446707
                                        - latitude: 138.854723
                                          longitude: 37.446707
                                      id: 1
                                    - coordinates:
                                        - latitude: 138.854723
                                          longitude: 37.446707
                                        - latitude: 138.854723
                                          longitude: 37.446707
                                        - latitude: 138.854723
                                          longitude: 37.446707
                                      id: 1
                                name: 路線名
                                operationalPoints:
                                    - elementID: 1
                                      name: バス停名
                                    - elementID: 1
                                      name: バス停名
                                    - elementID: 1
                                      name: バス停名
                                relations:
                                    - elementA: 1
                                      elementB: 2
                                    - elementA: 1
                                      elementB: 2
                                    - elementA: 1
                                      elementB: 2
                                    - elementA: 1
                                      elementB: 2
components:
    schemas:
        Coordinate:
            type: object
            properties:
                latitude:
                    type: number
                    description: 経度
                    example: 138.854723
                    format: float
                longitude:
                    type: number
                    description: 緯度
                    example: 37.446707
                    format: float
            example:
                latitude: 138.854723
                longitude: 37.446707
        CoordinateCollection:
            type: array
            items:
                $ref: '#/components/schemas/Coordinate'
            example:
                - latitude: 138.854723
                  longitude: 37.446707
                - latitude: 138.854723
                  longitude: 37.446707
                - latitude: 138.854723
                  longitude: 37.446707
        Element:
            type: object
            properties:
                coordinates:
                    $ref: '#/components/schemas/CoordinateCollection'
                id:
                    type: integer
                    description: id
                    example: 1
                    format: int64
            example:
                coordinates:
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                id: 1
        ElementCollection:
            type: array
            items:
                $ref: '#/components/schemas/Element'
            example:
                - coordinates:
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                  id: 1
                - coordinates:
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                  id: 1
                - coordinates:
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                  id: 1
                - coordinates:
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                    - latitude: 138.854723
                      longitude: 37.446707
                  id: 1
        Line:
            type: object
            properties:
                elements:
                    $ref: '#/components/schemas/ElementCollection'
                name:
                    type: string
                    description: 路線名
                    example: 路線名
                operationalPoints:
                    $ref: '#/components/schemas/OperationalpointCollection'
                relations:
                    $ref: '#/components/schemas/RelationCollection'
            example:
                elements:
                    - coordinates:
                        - latitude: 138.854723
                          longitude: 37.446707
                        - latitude: 138.854723
                          longitude: 37.446707
                        - latitude: 138.854723
                          longitude: 37.446707
                      id: 1
                    - coordinates:
                        - latitude: 138.854723
                          longitude: 37.446707
                        - latitude: 138.854723
                          longitude: 37.446707
                        - latitude: 138.854723
                          longitude: 37.446707
                      id: 1
                name: 路線名
                operationalPoints:
                    - elementID: 1
                      name: バス停名
                    - elementID: 1
                      name: バス停名
                    - elementID: 1
                      name: バス停名
                relations:
                    - elementA: 1
                      elementB: 2
                    - elementA: 1
                      elementB: 2
                    - elementA: 1
                      elementB: 2
                    - elementA: 1
                      elementB: 2
        Operationalpoint:
            type: object
            properties:
                elementID:
                    type: integer
                    description: elementID
                    example: 1
                    format: int64
                name:
                    type: string
                    description: バス停名
                    example: バス停名
            example:
                elementID: 1
                name: バス停名
        OperationalpointCollection:
            type: array
            items:
                $ref: '#/components/schemas/Operationalpoint'
            example:
                - elementID: 1
                  name: バス停名
                - elementID: 1
                  name: バス停名
                - elementID: 1
                  name: バス停名
                - elementID: 1
                  name: バス停名
        Relation:
            type: object
            properties:
                elementA:
                    type: integer
                    description: elementA
                    example: 1
                    format: int64
                elementB:
                    type: integer
                    description: elementB
                    example: 2
                    format: int64
            example:
                elementA: 1
                elementB: 2
        RelationCollection:
            type: array
            items:
                $ref: '#/components/schemas/Relation'
            example:
                - elementA: 1
                  elementB: 2
                - elementA: 1
                  elementB: 2
tags:
    - name: rosenzu
      description: 路線データ
